id: P003193
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20481
  title: རྣམ་འགྲེལ་གྱི་རྣམ་བཤད་གངས་ཅན་གྱི་རྒྱན
  author: ''
  volumes:
    b70fc9bc5814475a8bdf79986a144762:
      image_group_id: I1PD36349
      title: ''
      volume_number: 1
      total_pages: 508
      base_file: v001.txt
